// Types
export default {
    LOGIN: "login/LOGIN",
    LOGIN_FAILED: "login/LOGIN_FAILED",
    LOGIN_SUCCESS: "login/LOGIN_SUCCESS",

    LOGIN_CLEAR: "login/LOGIN_CLEAR",
    LOGIN_FIELD_CHANGED: "login/LOGIN_FIELD_CHANGED",

    LOGIN_SESSION_START: "login/LOGIN_SESSION_START",
    LOGIN_SESSION_END: "login/LOGIN_SESSION_END",

    LOGIN_WITH_SSO: "login/LOGIN_WITH_SSO",
    LOGIN_WITH_SSO_SUCCESS: "login/LOGIN_WITH_SSO_SUCCESS",
    LOGIN_WITH_SSO_FAILED: "login/LOGIN_WITH_SSO_FAILED",

    GET_USER_TOKEN: "home/GET_USER_TOKEN",
    GET_USER_TOKEN_SUCCESS: "home/GET_USER_TOKEN_SUCCESS",
    GET_USER_TOKEN_FAILED: "home/GET_USER_TOKEN_FAILED",

    HEADER_TOKEN: "home/HEADER_TOKEN"
}